# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0483f5d63629cd2e283e9c06c99341dbcc9c2db6640a1d81d54f37013fa25ddddc19f49327e39240d2ae54b9fb7f936358018086202255a38bebaabfba6769fb

test:
  secret_key_base: 3f7676236b52a0b97938e91d7c8c7035b57dab08a4fa349ab220420d758c1a8eed5e0ca6be2bd2a76b6268e0b8ffd85810b8b3b52f8835aea1d7bcfc8161622b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
